export const resList = [
  {
    "id": "res_101",
    "name": "The Burger Club",
    "imageUrl": "https://picsum.photos/seed/burger/200",
    "locality": "Koramangala",
    "areaName": "5th Block",
    "costForTwo": "₹300 for two",
    "cuisines": ["Burgers", "American", "Beverages"],
    "avgRating": 4.3,
    "totalRatingsString": "10K+",
    "deliveryTime": 24,
    "slaString": "20-25 mins",
    "discountHeader": "ITEMS",
    "discountSubHeader": "AT ₹129"
  },
  {
    "id": "res_102",
    "name": "Imperial Biryani House",
    "imageUrl": "https://picsum.photos/seed/biryani/200",
    "locality": "Indiranagar",
    "areaName": "100ft Road",
    "costForTwo": "₹450 for two",
    "cuisines": ["Biryani", "Mughlai", "North Indian"],
    "avgRating": 4.5,
    "totalRatingsString": "5K+",
    "deliveryTime": 35,
    "slaString": "30-35 mins",
    "discountHeader": "40% OFF",
    "discountSubHeader": "UPTO ₹80"
  },
  {
    "id": "res_103",
    "name": "Sagar Ratna Veg",
    "imageUrl": "https://picsum.photos/seed/veg/200",
    "locality": "Jayanagar",
    "areaName": "4th Block",
    "costForTwo": "₹250 for two",
    "cuisines": ["South Indian", "Pure Veg", "Chinese"],
    "avgRating": 4.1,
    "totalRatingsString": "1K+",
    "deliveryTime": 18,
    "slaString": "15-20 mins",
    "discountHeader": "FREE DELIVERY",
    "discountSubHeader": ""
  },
  {
    "id": "res_104",
    "name": "Pizza Hut",
    "imageUrl": "https://picsum.photos/seed/pizza/200",
    "locality": "HSR Layout",
    "areaName": "Sector 3",
    "costForTwo": "₹600 for two",
    "cuisines": ["Pizzas", "Fast Food", "Italian"],
    "avgRating": 3.9,
    "totalRatingsString": "15K+",
    "deliveryTime": 30,
    "slaString": "25-30 mins",
    "discountHeader": "DEAL OF THE DAY",
    "discountSubHeader": "FLAT ₹150 OFF"
  },
  {
    "id": "res_105",
    "name": "Wok Express",
    "imageUrl": "https://picsum.photos/seed/wok/200",
    "locality": "Whitefield",
    "areaName": "ITPL Main Rd",
    "costForTwo": "₹350 for two",
    "cuisines": ["Asian", "Chinese", "Thai"],
    "avgRating": 4.2,
    "totalRatingsString": "500+",
    "deliveryTime": 28,
    "slaString": "25-30 mins",
    "discountHeader": "ITEMS",
    "discountSubHeader": "STARTING AT ₹99"
  },
  {
    "id": "res_106",
    "name": "Sweet Truth Desserts",
    "imageUrl": "https://picsum.photos/seed/dessert/200",
    "locality": "Marathahalli",
    "areaName": "Outer Ring Road",
    "costForTwo": "₹200 for two",
    "cuisines": ["Desserts", "Ice Cream", "Bakery"],
    "avgRating": 4.4,
    "totalRatingsString": "2K+",
    "deliveryTime": 22,
    "slaString": "20-25 mins",
    "discountHeader": "20% OFF",
    "discountSubHeader": "ABOVE ₹299"
  },
  {
    "id": "res_107",
    "name": "Subway",
    "imageUrl": "https://picsum.photos/seed/subway/200",
    "locality": "BTM Layout",
    "areaName": "2nd Stage",
    "costForTwo": "₹350 for two",
    "cuisines": ["Healthy Food", "Salads", "Snacks"],
    "avgRating": 4.0,
    "totalRatingsString": "8K+",
    "deliveryTime": 20,
    "slaString": "15-20 mins",
    "discountHeader": "EVERYDAY VALUE",
    "discountSubHeader": "2 SUBS FOR ₹350"
  },
  {
    "id": "res_108",
    "name": "The Bowl Company",
    "imageUrl": "https://picsum.photos/seed/bowl/200",
    "locality": "Electronic City",
    "areaName": "Phase 1",
    "costForTwo": "₹300 for two",
    "cuisines": ["Continental", "Pan-Asian", "North Indian"],
    "avgRating": 4.6,
    "totalRatingsString": "12K+",
    "deliveryTime": 26,
    "slaString": "25-30 mins",
    "discountHeader": "FLAT 50% OFF",
    "discountSubHeader": "WELCOME ONE"
  }
]